### ISSUE TITLE
Decide on data formats

### ISSUE THREAD

**Issue by fwege** [SEGuRo-Projekt/Plattform#21]
Decide which data formats are used to store files of different size and content.

- HDF5: https://www.hdfgroup.org/solutions/hdf5/
- Parquet: https://parquet.apache.org/
- CSV
- JSON
- MAT: https://de.mathworks.com/help/matlab/import_export/mat-file-versions.html

See also:
- https://docs.aws.amazon.com/AmazonS3/latest/userguide/selecting-content-from-objects.html
- https://min.io/docs/minio/linux/reference/minio-mc/mc-sql.html

**Comment by stv0g** [comment]
Decision after meeting on 2023-06-12: **Parquet**
